# Generated by Django 5.1.1 on 2024-09-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barchart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Barchart_data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='CandleStickchart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Candle_data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Piechart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Piechart_data', models.JSONField()),
            ],
        ),
        migrations.RenameField(
            model_name='linechart',
            old_name='data',
            new_name='Linechart_data',
        ),
    ]
